<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultItems>true</EnableDefaultItems>
    <RazorCompileOnBuild>true</RazorCompileOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**\*.cs" />
    <Compile Include="TechServe.Web\**\*.cs" />
    <EmbeddedResource Remove="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
  </ItemGroup>
</Project>
